stages:
  prepare_data:
    cmd: bash prepare_data.sh
    deps:
    - ./vsa_encoder/dataset/paired_dsprites.py
    - prepare_data.sh
    outs:
    - data/
  train:
    cmd: python3 -m vsa_encoder.train
    deps:
    - conf/
    - vsa_encoder/model/
    - vsa_encoder/train.py
    - vsa_encoder/utils.py
