dataset:
  mode: "dsprites"
  path_to_dataset: "./data/paired_dsprites"
  train_size: 100_000

experiment:
  seed: 0
  batch_size: 64
  gradient_clip: 0.0
  steps_per_epoch: 0

  devices: 0
  max_epochs: 400
  accelerator: gpu
  profiler: null

model:
  image_size: (1, 64, 64)
  n_features: 5
  bind_mode: fourier
  latent_dim: 1024
  lr: 0.00025
  kld_coef: 0.001
  monitor: "Validation/Total"

checkpoints:
  save_top_k: 1
  every_k_epochs: 10
  check_val_every_n_epochs: 5
  ckpt_path: null




